@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-06-26 20:24
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=ollama_manager_pro"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDYtMjYgMjA6MjQNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9S2V5c3RvbmVfb2xs
        echo YW1hX21hbmFnZXJfcHJvIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1m
        echo aWxlIg0Kc2V0ICJBUFBfRU5UUlk9c3JjXG1haW4ucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCg0K
        echo c2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhp
        echo c3QgIiVQWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFkl
        echo Ig0KICAgIGVjaG8uDQogICAgZWNobyBGaXggd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNobyAgICIlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4
        echo ZSIgLW0gcGlwIGluc3RhbGwgLS11cGdyYWRlIHBpcA0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxT
        echo Y3JpcHRzXHB5dGhvbi5leGUiIC1tIHBpcCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAg
        echo ICBlY2hvLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCmlmIC9JICIlRU5UUllfTU9E
        echo RSUiPT0iZmlsZSIgaWYgbm90IGV4aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgIGVjaG8gW0VSUk9S
        echo XSBFbnRyeSBmaWxlIG5vdCBmb3VuZDogIiVBUFBfRU5UUlklIg0KICAgIGVjaG8gRWRpdCBydW4u
        echo YmF0IG9yIHJ1biB3aXRoIHRoZSBjb3JyZWN0IGVudHJ5IGZpbGUuDQogICAgcGF1c2UNCiAgICBl
        echo eGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gUlVOIg0KZWNobyA9PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVj
        echo aG8gIFJ1bm5pbmcgOiAlUFJPSkVDVF9OQU1FJQ0KZWNobyAgUHJvamVjdCA6ICVDRCUNCmVjaG8g
        echo IFB5dGhvbiAgOiAlUFklDQplY2hvICBNb2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRy
        echo eSAgIDogJUFQUF9FTlRSWSUNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBB
        echo cmdzICAgIDogJVJVTk5FUl9BUkdTJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8uDQoNCnNldCAiRVhJVENPREU9
        echo MCINCg0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJtb2R1bGUiICgNCiAgICAiJVBZJSIgLW0gJUFQ
        echo UF9FTlRSWSUgJSoNCikgZWxzZSBpZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgKA0KICAg
        echo IGlmIGRlZmluZWQgUlVOTkVSX0FSR1MgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUg
        echo IVJVTk5FUl9BUkdTISAlKg0KICAgICkgZWxzZSAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VO
        echo VFJZJSAlKg0KICAgICkNCikgZWxzZSAoDQogICAgIiVQWSUiICIlQVBQX0VOVFJZJSIgJSoNCikN
        echo Cg0Kc2V0ICJFWElUQ09ERT0hRVJST1JMRVZFTCEiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo UHJvY2VzcyBleGl0ZWQgd2l0aCBjb2RlOiAhRVhJVENPREUhDQplY2hvID09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4
        echo aXQgL2IgIUVYSVRDT0RFIQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDYtMjYgMjA6MjQNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA2LTI2
        echo IDIwOjI0DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9S2V5c3RvbmVfb2xsYW1hX21hbmFnZXJfcHJvIg0Kc2V0ICJWRU5WX0RJUj0udmVudiIN
        echo CnNldCAiQUNUSVZBVEU9JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNcYWN0aXZhdGUuYmF0Ig0KDQpp
        echo ZiBub3QgZXhpc3QgIiVBQ1RJVkFURSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3
        echo YXMgbm90IGZvdW5kOg0KICAgIGVjaG8gICAgICAgICAiJUFDVElWQVRFJSINCiAgICBlY2hvLg0K
        echo ICAgIGVjaG8gQ3JlYXRlIGl0IHdpdGg6DQogICAgZWNobyAgICAgICAgIHB5dGhvbiAtbSB2ZW52
        echo ICIlVkVOVl9ESVIlIg0KICAgIGVjaG8uDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0K
        echo dGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gVkVOViBTSEVMTCINCmNhbGwgIiVBQ1RJVkFURSUiDQoN
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQplY2hvICBQcm9qZWN0IHNoZWxsIGFjdGl2YXRlZA0KZWNobyAgUHJvamVjdDog
        echo IiVDRCUiDQplY2hvICBQeXRob24gOg0Kd2hlcmUgcHl0aG9uDQplY2hvICBUeXBlICJleGl0IiB0
        echo byBsZWF2ZSB0aGlzIHNoZWxsLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8uDQpjbWQgL2sNCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNi0yNiAyMDoyNA0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1LZXlzdG9u
        echo ZV9vbGxhbWFfbWFuYWdlcl9wcm8iDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJQWT0lQ0Ql
        echo XCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgN
        echo CiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVW
        echo RU5WX0RJUiUiDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNU
        echo X05BTUUlIC0gU1lOQyINCg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFN5bmNpbmc6ICVQUk9KRUNUX05BTUUl
        echo DQplY2hvICBQeXRob24gOiAlUFklDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0KZWNobyBbMS8zXSBVcGdy
        echo YWRpbmcgcGlwLi4uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PQ0KIiVQWSUiIC1tIHBpcCBpbnN0YWxsIC0tdXBncmFkZSBw
        echo aXANCmVjaG8uDQoNCmlmIGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiAoDQogICAgZWNobyBbMi8z
        echo XSBJbnN0YWxsaW5nIGZyb20gcmVxdWlyZW1lbnRzLnR4dC4uLg0KICAgIGVjaG8gPT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQogICAg
        echo IiVQWSUiIC1tIHBpcCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KKSBl
        echo bHNlICgNCiAgICBlY2hvIFsyLzNdIFNLSVBQRUQ6IE5vIHJlcXVpcmVtZW50cy50eHQgZm91bmQu
        echo DQogICAgZWNobyAgICAgICBDcmVhdGUgb25lIHdpdGg6IHBpcC5iYXQgZnJlZXplIF4+IHJlcXVp
        echo cmVtZW50cy50eHQNCiAgICBlY2hvLg0KKQ0KDQplY2hvIFszLzNdIERlcGVuZGVuY3kgaGVhbHRo
        echo IGNoZWNrLi4uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PQ0KIiVQWSUiIC1tIHBpcCBjaGVjaw0KZWNoby4NCg0KZWNobyA9
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT0NCmVjaG8gIFNZTkMgQ09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA2LTI2IDIwOjI0DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPUtleXN0b25lX29sbGFt
        echo YV9tYW5hZ2VyX3BybyINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9Zmls
        echo ZSINCnNldCAiQVBQX0VOVFJZPXNyY1xtYWluLnB5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0iDQpzZXQg
        echo IlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmVjaG8gPT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hv
        echo ICBQUk9KRUNUIERPQ1RPUjogJVBST0pFQ1RfTkFNRSUNCmVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQcm9qZWN0
        echo IDogJUNEJQ0KZWNobyAgTW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkgICA6ICVB
        echo UFBfRU5UUlklDQppZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJncyAgICA6
        echo ICVSVU5ORVJfQVJHUyUNCmVjaG8uDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8g
        echo W0ZBSUxdIHZlbnYgbm90IGZvdW5kIGF0OiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3Jl
        echo YXRlIGl0IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAg
        echo IHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCmVjaG8gW09LXSB2ZW52IGZvdW5kOiAiJVBZJSIN
        echo CmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQeXRob24gRW52aXJvbm1lbnQNCmVjaG8gLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoi
        echo JVBZJSIgLWMgImltcG9ydCBzeXM7IHByaW50KCdFeGVjdXRhYmxlIDonLCBzeXMuZXhlY3V0YWJs
        echo ZSk7IHByaW50KCdWZXJzaW9uICAgIDonLCBzeXMudmVyc2lvbi5zcGxpdCgpWzBdKTsgcHJpbnQo
        echo J1ByZWZpeCAgICAgOicsIHN5cy5wcmVmaXgpIg0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIHBp
        echo cCB2ZXJzaW9uDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1tIHBpcCAtLXZlcnNpb24NCmVjaG8uDQoNCmVj
        echo aG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tDQplY2hvICBJbnN0YWxsZWQgUGFja2FnZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlw
        echo IGxpc3QNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBEZXBlbmRlbmN5IEhlYWx0aA0KZWNobyAt
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0NCiIlUFklIiAtbSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBFbnRyeSBQ
        echo b2ludCBDaGVjaw0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0NCmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIgKA0KICAg
        echo IGlmIGV4aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgICAgICBlY2hvIFtPS10gRW50cnkgZmlsZSBm
        echo b3VuZDogIiVBUFBfRU5UUlklIg0KICAgICkgZWxzZSAoDQogICAgICAgIGVjaG8gW0ZBSUxdIEVu
        echo dHJ5IGZpbGUgTk9UIGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgKQ0KKSBlbHNlICgNCiAgICAi
        echo JVBZJSIgLWMgImltcG9ydCBpbXBvcnRsaWIudXRpbCwgc3lzOyBuYW1lPXInJUFQUF9FTlRSWSUn
        echo OyBzcGVjPWltcG9ydGxpYi51dGlsLmZpbmRfc3BlYyhuYW1lKTsgcHJpbnQoKCdbT0tdIE1vZHVs
        echo ZSBmb3VuZDogJyBpZiBzcGVjIGVsc2UgJ1tGQUlMXSBNb2R1bGUgTk9UIGZvdW5kOiAnKSArIG5h
        echo bWUpOyBzeXMuZXhpdCgwIGlmIHNwZWMgZWxzZSAxKSIgMj5udWwNCiAgICBpZiBlcnJvcmxldmVs
        echo IDEgZWNobyBbRkFJTF0gTW9kdWxlIGltcG9ydCB0ZXN0IGZhaWxlZC4NCiAgICBpZiAvSSAiJUVO
        echo VFJZX01PREUlIj09InJ1bm5lciIgZWNobyBbSU5GT10gUnVubmVyIGFyZ3M6ICIlUlVOTkVSX0FS
        echo R1MlIg0KKQ0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIFByb2plY3QgRmlsZXMNCmVjaG8gLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo DQppZiBleGlzdCAidXYubG9jayIgICAgICAgICAgZWNobyBbT0tdICAgdXYubG9jayBmb3VuZA0K
        echo aWYgZXhpc3QgInB5cHJvamVjdC50b21sIiAgIGVjaG8gW09LXSAgIHB5cHJvamVjdC50b21sIGZv
        echo dW5kDQppZiBleGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgZWNobyBbT0tdICAgcmVxdWlyZW1lbnRz
        echo LnR4dCBmb3VuZA0KaWYgbm90IGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtXQVJOXSBy
        echo ZXF1aXJlbWVudHMudHh0IG1pc3NpbmcNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQeVF0NiBX
        echo ZWJFbmdpbmUgQ2hlY2sNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLWMgImZyb20gUHlRdDYgaW1wb3J0IFF0
        echo Q29yZTsgcHJpbnQoJ1B5UXQ6JywgUXRDb3JlLlBZUVRfVkVSU0lPTl9TVFIpOyBwcmludCgnUXQg
        echo IDonLCBRdENvcmUuUVRfVkVSU0lPTl9TVFIpOyBmcm9tIFB5UXQ2LlF0V2ViRW5naW5lV2lkZ2V0
        echo cyBpbXBvcnQgUVdlYkVuZ2luZVZpZXc7IHByaW50KCdbT0tdIFdlYkVuZ2luZSBpbXBvcnRlZCBz
        echo dWNjZXNzZnVsbHkuJykiIDI+JjENCmlmIGVycm9ybGV2ZWwgMSAoDQogICAgZWNobyBbRkFJTF0g
        echo UHlRdDYgV2ViRW5naW5lIGNoZWNrIGZhaWxlZC4NCiAgICBlY2hvICAgICAgICBSdW4gbWFudWFs
        echo bHkgZm9yIGZ1bGwgdHJhY2ViYWNrOg0KICAgIGVjaG8gICAgICAgICIlUFklIiAtYyAiZnJvbSBQ
        echo eVF0Ni5RdFdlYkVuZ2luZVdpZGdldHMgaW1wb3J0IFFXZWJFbmdpbmVWaWV3Ig0KKSBlbHNlICgN
        echo CiAgICBlY2hvIFtPS10gUHlRdDYgV2ViRW5naW5lIGlzIGF2YWlsYWJsZS4NCikNCmVjaG8uDQoN
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQplY2hvICBET0NUT1IgQ09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAv
        echo YiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
rem (test.bat not included)
echo ============================================================
pause
exit /b 0
